### ISSUE TITLE
Unclear how to do SWD + SWO together

### ISSUE THREAD

**Issue by philipag** [diegoherranz/steppenprobe#1]
The main readme says that SWD and SWO can work simultaneously but it is unclear how to tell this to openocd?  E.g. how to specify the FT channel to use for SWO?

**Comment by diegoherranz** [comment]
I have just done a big update of the README, explaining how to use SWD+SWO.
Hopefully that answers your question. Please re-open this and let me know otherwise.
Thanks!

**Comment by diegoherranz** [comment]
By the way, see the section I've added explaining the FTDI channels too.

**Comment by philipag** [comment]
Thanks for that Diego.  Yours is a better explanation than any other I have found on the net.  I mistakenly assumed that openocd would be able to directly output the SWO trace output via GDB just like a segger probe can.
